# Create Contact

# POST http://localhost:3000/contacts
# Content-Type: application/json

# {
#   "firstName": "Patchoulii",
#   "lastName": "Knowledge",
#   "email": "ScarletMansion@gmail.com",
#   "favoriteColor": "Purple",
#   "birthday": "09/01/2002"
# }

# Update Contact

# PUT http://localhost:3000/contacts/682970b8a58772294edf42b2
# Content-Type: application/json

# {
#   "firstName": "Patchoulii",
#   "lastName": "Knowledge",
#   "email": "Knowledge@gmail.com",
#   "favoriteColor": "Dark Purple",
#   "birthday": "01/18/2008"
# }


#Delete Contact

# DELETE http://localhost:3000/contacts/682970b8a58772294edf42b2

